//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosPediG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factura()
        {
            this.DetalleFactura = new HashSet<DetalleFactura>();
        }
    
        public int Id { get; set; }
        public int NumeroFactura { get; set; }
        public System.DateTime FechaFactura { get; set; }
        public double TotalNeto { get; set; }
        public int TipoDePagoId { get; set; }
        public int TipoEntregaId { get; set; }
        public int ClienteId { get; set; }
        public string DireccionPedido { get; set; }
        public int EstadoFacturaId { get; set; }
        public System.DateTime FechaEntregaPedido { get; set; }
        public string User { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleFactura> DetalleFactura { get; set; }
        public virtual TipoEntrega TipoEntrega { get; set; }
        public virtual TipoDePago TipoDePago { get; set; }
        public virtual EstadoFactura EstadoFactura { get; set; }
    }
}
